# This is the configuration used to check the rubocop source code.

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - lib
    - test

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false
